[theme]
base = "light"
primaryColor = "#006460"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1A1A1A"
font = "sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
